from models.dense_autoencoder import DenseSupervisedModel, DenseAutoencoderModel
from models.rotation import RotationSupervisedModel, RotationSelfSupervisedModel
# from conv_autoencoder import ConvSupervisedModel, ConvAutoencoderModel
